test_query = "What are the main factors contributing to salmonella rates in Missouri in a statistical sense?"

[router]
model = "gemma3:12b-it-qat"
provider = "ollama"

[explorer]
model = "o3-mini"
provider = "openai"

[analyzer]
model = "o3-mini"
provider = "openai"

[planner]
model = "o3-mini-2025-01-31"
provider = "openai"

[executor]
model = "o3-mini"
provider = "openai"

[aggregator]
model = "gemma3:12b"
provider = "ollama"

